/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'Submitchannel': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'yt.submit'; data: never }>
    'ResolveChannel': EventHandler<never, { topic: 'yt.channel.resolved'; data: never }>
    'FetchVideos': EventHandler<never, { topic: 'yt.videos.fetched'; data: never }>
    'AI Title Fetch & Generate': EventHandler<never, { topic: 'yt.titles.ready'; data: never }>
    'Send Email with Improved Titles': EventHandler<never, never>
  }
    
}